loader:
  num_samples_per_class: 200
  batch_size: 32

dataset:
  name: "cifar10"
  path: "datasets"
  img_size: 224
  img_channels: 3
  num_classes: 10

model:
  embedding_dimension: 128
  patch_embedding_drop_rate: 0.1
  patch_height: 16
  patch_width: 16

attention:
  n_heads: 8
  head_dimension: 64
  drop_rate: 0.1

transformer:
  ffn_hidden_dimension: 256
  drop_rate: 0.1
  n_layers: 7

